local T = require("helpers")
local Poller = require("poller")

-- A stand-in engine that records queries instead of sending them.
local function fakeEngine()
  local e = { ready = true, queries = {} }
  function e:IsReady() return self.ready end
  function e:Query(key) self.queries[#self.queries + 1] = key; return true end
  function e:drain()
    local q = self.queries
    self.queries = {}
    return table.concat(q, ",")
  end
  return e
end

T.test("with unknown power only power is polled, every second", function()
  local e = fakeEngine()
  local p = Poller.New(e, {})
  p:Tick(0)
  T.eq(e:drain(), "power")
  p:Tick(0.9)
  T.eq(e:drain(), "")
  p:Tick(1.0)
  T.eq(e:drain(), "power")
end)

T.test("becoming On makes every item due and then paces them", function()
  local e = fakeEngine()
  local p = Poller.New(e, {}, { NormalInterval = 2 })
  p:Tick(0)
  e:drain()
  p:SetPower("On")
  p:Tick(1)
  T.eq(e:drain(), "powi,lightstate,input,shutter,freeze,diag1,diag2,tempIntake,tempExhaust,hoursProj,hoursLight1")
  p:Tick(2)
  T.eq(e:drain(), "power")
  p:Tick(3)
  T.eq(e:drain(), "powi,lightstate,input,shutter,freeze")
  p:Tick(4)
  T.eq(e:drain(), "power")
  p:Tick(5)
  T.eq(e:drain(), "powi,lightstate,input,shutter,freeze")
  p:Tick(6)
  T.eq(e:drain(), "power,diag1,diag2")
end)

T.test("the normal interval is configurable", function()
  local e = fakeEngine()
  local p = Poller.New(e, {}, { NormalInterval = 5 })
  p:SetPower("On")
  p:Tick(0)
  e:drain()
  p:Tick(4.9)
  T.eq(e:drain(), "")
  p:Tick(5)
  T.eq(e:drain(), "power,powi,lightstate,input,shutter,freeze,diag1,diag2")
end)

T.test("model features add their own status polls", function()
  local e = fakeEngine()
  local p = Poller.New(e, {}, { NormalInterval = 2, Features = { TempOptics = true, Light2Hours = true } })
  p:SetPower("On")
  p:Tick(0)
  T.eq(e:drain(), "power,powi,lightstate,input,shutter,freeze,diag1,diag2,tempIntake,tempExhaust,tempOptics,hoursProj,hoursLight1,hoursLight2")
  p:PollNow("tempLight2")
  T.eq(e:drain(), "", "a feature the model lacks cannot be polled")
end)

T.test("in standby only power and the power/light lifecycle are polled, every ten seconds", function()
  local e = fakeEngine()
  local p = Poller.New(e, {})
  p:SetPower("Standby")
  p:Tick(0)
  T.eq(e:drain(), "power,powi,lightstate")
  p:Tick(9.9)
  T.eq(e:drain(), "")
  p:Tick(10)
  T.eq(e:drain(), "power,powi,lightstate")
end)

T.test("nothing is polled while the engine is not ready", function()
  local e = fakeEngine()
  e.ready = false
  local p = Poller.New(e, {})
  p:Tick(0)
  p:Tick(5)
  T.eq(e:drain(), "")
  e.ready = true
  p:Tick(6)
  T.eq(e:drain(), "power")
end)

T.test("Reset forgets power state and timing", function()
  local e = fakeEngine()
  local p = Poller.New(e, {})
  p:SetPower("On")
  p:Tick(0)
  e:drain()
  p:Reset()
  p:Tick(0.1)
  T.eq(e:drain(), "power")
end)

T.test("PollNow queries one item immediately", function()
  local e = fakeEngine()
  local p = Poller.New(e, {})
  p:SetPower("On")
  p:PollNow("shutter")
  T.eq(e:drain(), "shutter")
  p:PollNow("nonexistent")
  T.eq(e:drain(), "")
end)

T.test("poll results reach the handler for that key", function()
  local got = {}
  local e = { queries = {} }
  function e:IsReady() return true end
  function e:Query(key, spec, cb) cb(true, "value-" .. key, "raw") return true end
  local p = Poller.New(e, { power = function(ok, v, raw) got[#got + 1] = v .. "/" .. raw end })
  p:Tick(0)
  T.eq(got[1], "value-power/raw")
end)

T.test("a boosted key is polled at the high rate until it ends", function()
  local e = fakeEngine()
  local p = Poller.New(e, {}, { NormalInterval = 2, HighRateInterval = 0.5 })
  p:SetPower("On")
  p:Tick(0)
  e:drain()
  p:Boost("shutter", 10)
  p:Tick(0.5)
  T.eq(e:drain(), "shutter")
  p:Tick(0.9)
  T.eq(e:drain(), "")
  p:Tick(1.0)
  T.eq(e:drain(), "shutter")
  p:EndBoost("shutter")
  T.falsy(p:IsBoosted("shutter"))
  p:Tick(1.5)
  T.eq(e:drain(), "", "back to the normal interval")
  p:Tick(2.0)
  T.eq(e:drain(), "power,powi,lightstate,input,freeze")
end)

T.test("a boost times out and then falls back to the normal interval", function()
  local e = fakeEngine()
  local p = Poller.New(e, {}, { NormalInterval = 2, HighRateInterval = 0.5 })
  p:SetPower("On")
  p:Tick(0)
  e:drain()
  p:Boost("shutter", 1)
  p:Tick(0.5)
  T.eq(e:drain(), "shutter")
  p:Tick(1.0)
  T.eq(e:drain(), "shutter")
  T.truthy(p:IsBoosted("shutter"))
  p:Tick(1.4)
  T.falsy(p:IsBoosted("shutter"))
  T.eq(e:drain(), "")
end)

T.test("boosting works even where the key is not normally polled", function()
  local e = fakeEngine()
  local p = Poller.New(e, {}, { HighRateInterval = 0.5 })
  p:SetPower("Standby")
  p:Tick(0)
  e:drain()
  p:Boost("input", 10)
  p:Tick(0.5)
  T.eq(e:drain(), "input")
end)

T.test("Reset ends boosts", function()
  local e = fakeEngine()
  local p = Poller.New(e, {})
  p:Boost("power", 10)
  p:Reset()
  T.falsy(p:IsBoosted("power"))
end)

return T.finish()
