local T = require("helpers")
local Protocol = require("protocol")
local Models = require("models")

T.test("Frame wraps a command with the assumed prefix and terminator", function()
  T.eq(Protocol.Frame("PON"), "00PON\r")
end)

T.test("Unframe strips CR and LF", function()
  T.eq(Protocol.Unframe("001\r"), "001")
  T.eq(Protocol.Unframe("001\r\n"), "001")
  T.eq(Protocol.Unframe("HD1"), "HD1")
end)

T.test("greeting: protect off and on", function()
  T.eq(Protocol.ParseGreeting("NTCONTROL 0").protected, false)
  T.eq(Protocol.ParseGreeting("NTCONTROL 1 a1b2c3d4").protected, true)
  T.eq(Protocol.ParseGreeting("001"), nil)
end)

T.test("error codes are recognised and diagnostics are not mistaken for errors", function()
  T.eq(Protocol.ErrorCode("ER401"), "ER401")
  T.eq(Protocol.ErrorCode("ER403"), "ER403")
  T.eq(Protocol.ErrorCode("ERRA"), "ERRA")
  T.eq(Protocol.ErrorCode("ERRS1=00000000"), nil)
  T.eq(Protocol.ErrorCode("001"), nil)
end)

T.test("power parser", function()
  local parse = Protocol.Queries.power.parse
  T.eq(parse("001"), "On")
  T.eq(parse("000"), "Standby")
  T.eq(parse("002"), nil)
  T.eq(parse(""), nil)
end)

T.test("flag parser distinguishes false from invalid", function()
  local parse = Protocol.Queries.shutter.parse
  T.eq(parse("1"), true)
  T.eq(parse("0"), false)
  T.eq(parse("2"), nil)
  T.eq(Protocol.Queries.freeze.parse("x"), nil)
end)

T.test("input and diagnostic parsers", function()
  T.eq(Protocol.Queries.input.parse("HD1"), "HD1")
  T.eq(Protocol.Queries.input.parse("DM1,SD1"), "DM1,SD1")
  T.eq(Protocol.Queries.input.parse("bad reply!"), nil)
  T.eq(Protocol.Queries.diag1.parse("ERRS1=0000"), "0000")
  T.eq(Protocol.Queries.diag1.parse("ERRS2=0000"), nil)
  T.eq(Protocol.Queries.diag2.parse("ERRS2=abc"), "abc")
end)

T.test("query and command strings match the model packages", function()
  T.eq(Protocol.Queries.power.line, "QPW")
  T.eq(Protocol.Queries.input.line, "QIN")
  T.eq(Protocol.Queries.shutter.line, "QSH")
  T.eq(Protocol.Queries.freeze.line, "QFZ")
  T.eq(Protocol.Queries.diag1.line, "QVX:ERRS1")
  T.eq(Protocol.Queries.diag2.line, "QVX:ERRS2")
  T.eq(Protocol.Commands.PowerOn.line, "PON")
  T.eq(Protocol.Commands.PowerOff.line, "POF")
  T.eq(Protocol.Commands.Menu.line, "OMN")
  T.eq(Protocol.Commands.Enter.line, "OEN")
  T.eq(Protocol.Commands.Up.line, "OCU")
  T.eq(Protocol.Commands.Down.line, "OCD")
  T.eq(Protocol.Commands.Left.line, "OCL")
  T.eq(Protocol.Commands.Right.line, "OCR")
  T.eq(Protocol.Commands.Default.line, "OST")
  T.eq(Protocol.Commands.AutoSetup.line, "OAS")
  T.eq(Protocol.ShutterCommand(true).line, "OSH:1")
  T.eq(Protocol.ShutterCommand(false).line, "OSH:0")
  T.eq(Protocol.FreezeCommand(true).line, "OFZ:1")
  T.eq(Protocol.FreezeCommand(false).line, "OFZ:0")
  T.eq(Protocol.InputCommand("DM1,SD1").line, "IIS:DM1,SD1")
end)

T.test("lens values follow the documented speed table", function()
  T.eq(Protocol.LensCommand("LNSI4", 1, "Slow").line, "VXX:LNSI4=+00000")
  T.eq(Protocol.LensCommand("LNSI4", -1, "Slow").line, "VXX:LNSI4=+00001")
  T.eq(Protocol.LensCommand("LNSI4", 1, "Normal").line, "VXX:LNSI4=+00100")
  T.eq(Protocol.LensCommand("LNSI5", -1, "Normal").line, "VXX:LNSI5=+00101")
  T.eq(Protocol.LensCommand("LNSI2", 1, "Fast").line, "VXX:LNSI2=+00200")
  T.eq(Protocol.LensCommand("LNSI3", -1, "Fast").line, "VXX:LNSI3=+00201")
  T.eq(Protocol.LensCommand("LNSI4", 1, "bogus").line, "VXX:LNSI4=+00100")
end)

T.test("only idempotent commands are retried", function()
  T.truthy(Protocol.Commands.PowerOn.idempotent)
  T.truthy(Protocol.ShutterCommand(true).idempotent)
  T.falsy(Protocol.Commands.Menu.idempotent)
  T.falsy(Protocol.LensCommand("LNSI4", 1, "Normal").idempotent)
end)

T.test("models: codes, ordering and lens mapping", function()
  T.eq(#Models.Ids, 2)
  local req = Models.Get("PT-REQ80")
  T.eq(req.Inputs[1].Code, "HD1")
  T.eq(req.Inputs[3].Code, "DP1")
  T.eq(req.OptionalInputs[2].Code, "DM1,DL1")
  local rq = Models.Get("PT-RQ35K2")
  T.eq(rq.Inputs[2].Code, "DL1")
  T.eq(rq.OptionalInputs[1].Code, "AU1,HD1")
  T.eq(req.Lens.Focus, "LNSI4")
  T.eq(rq.Lens.VerticalShift, "LNSI3")
  T.eq(Models.Get("nonsense").Id, Models.Default)
  T.truthy(rq.Features.AutoSetup)
  T.falsy(req.Features.AutoSetup)
end)

T.test("optional input labels are unique across models", function()
  local seen = {}
  for _, id in ipairs(Models.Ids) do
    for _, opt in ipairs(Models.ById[id].OptionalInputs) do
      local name = Models.OptionalPropertyName(opt)
      T.falsy(seen[name], "duplicate property " .. name)
      seen[name] = true
    end
  end
end)

T.test("status query lines match the reference", function()
  local q = Protocol.Queries
  T.eq(q.powi.line, "QVX:POWI1")
  T.eq(q.lightstate.line, "Q$S")
  T.eq(q.tempIntake.line, "QTM:0")
  T.eq(q.tempExhaust.line, "QTM:1")
  T.eq(q.tempOptics.line, "QTM:2")
  T.eq(q.tempLight1.line, "QTM:11")
  T.eq(q.tempLight2.line, "QTM:12")
  T.eq(q.hoursProj.line, "QVX:RTMS1")
  T.eq(q.hoursLight1.line, "QVX:LRTS3=00")
  T.eq(q.hoursLight2.line, "QVX:LRTS3=01")
end)

T.test("power lifecycle parser", function()
  local parse = Protocol.Queries.powi.parse
  T.eq(parse("POWI1=+00001"), "Off")
  T.eq(parse("POWI1=+00002"), "Warming Up")
  T.eq(parse("POWI1=+00003"), "On")
  T.eq(parse("POWI1=+00004"), "Cooling")
  T.eq(parse("POWI1=+00009"), "Unknown")
  T.eq(parse("garbage"), nil)
end)

T.test("light lifecycle parser", function()
  local parse = Protocol.Queries.lightstate.parse
  T.eq(parse("0"), "Off")
  T.eq(parse("1"), "Starting")
  T.eq(parse("2"), "On")
  T.eq(parse("3"), "Cooling")
  T.eq(parse("7"), "Unknown")
  T.eq(parse("x"), nil)
end)

T.test("temperature parser keeps both values and allows negatives", function()
  local parse = Protocol.Queries.tempIntake.parse
  local t = parse("35/95")
  T.eq(t.c, 35)
  T.eq(t.f, 95)
  t = parse("-5/23")
  T.eq(t.c, -5)
  T.eq(t.f, 23)
  T.eq(parse("hot"), nil)
end)

T.test("hours parsers", function()
  T.eq(Protocol.Queries.hoursProj.parse("RTMS1=1234"), 1234)
  T.eq(Protocol.Queries.hoursLight1.parse("LRTS3=00:567"), 567)
  T.eq(Protocol.Queries.hoursLight2.parse("LRTS3=01:89"), 89)
  T.eq(Protocol.Queries.hoursLight1.parse("LRTS3=01:89"), nil)
  T.eq(Protocol.Queries.hoursProj.parse("nope"), nil)
end)

return T.finish()
